<?php

namespace DoctrineORMModule\Proxy\__CG__\Sistema\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Control extends \Sistema\Entity\Control implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Sistema\\Entity\\Control' . "\0" . 'nctrcodigo', '' . "\0" . 'Sistema\\Entity\\Control' . "\0" . 'nctrtipo', '' . "\0" . 'Sistema\\Entity\\Control' . "\0" . 'cctrjerarquia', '' . "\0" . 'Sistema\\Entity\\Control' . "\0" . 'cctrnombre', '' . "\0" . 'Sistema\\Entity\\Control' . "\0" . 'cctrvalor', '' . "\0" . 'Sistema\\Entity\\Control' . "\0" . 'nctrdescripcion', '' . "\0" . 'Sistema\\Entity\\Control' . "\0" . 'nctrestado', '' . "\0" . 'Sistema\\Entity\\Control' . "\0" . 'padre', 'hijos', 'rolcontrols', 'perusuaccesos');
        }

        return array('__isInitialized__', '' . "\0" . 'Sistema\\Entity\\Control' . "\0" . 'nctrcodigo', '' . "\0" . 'Sistema\\Entity\\Control' . "\0" . 'nctrtipo', '' . "\0" . 'Sistema\\Entity\\Control' . "\0" . 'cctrjerarquia', '' . "\0" . 'Sistema\\Entity\\Control' . "\0" . 'cctrnombre', '' . "\0" . 'Sistema\\Entity\\Control' . "\0" . 'cctrvalor', '' . "\0" . 'Sistema\\Entity\\Control' . "\0" . 'nctrdescripcion', '' . "\0" . 'Sistema\\Entity\\Control' . "\0" . 'nctrestado', '' . "\0" . 'Sistema\\Entity\\Control' . "\0" . 'padre', 'hijos', 'rolcontrols', 'perusuaccesos');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Control $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNctrcodigo()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getNctrcodigo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNctrcodigo', array());

        return parent::getNctrcodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNctrtipo($nctrtipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNctrtipo', array($nctrtipo));

        return parent::setNctrtipo($nctrtipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNctrtipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNctrtipo', array());

        return parent::getNctrtipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCctrjerarquia($cctrjerarquia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCctrjerarquia', array($cctrjerarquia));

        return parent::setCctrjerarquia($cctrjerarquia);
    }

    /**
     * {@inheritDoc}
     */
    public function getCctrjerarquia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCctrjerarquia', array());

        return parent::getCctrjerarquia();
    }

    /**
     * {@inheritDoc}
     */
    public function setCctrnombre($cctrnombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCctrnombre', array($cctrnombre));

        return parent::setCctrnombre($cctrnombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getCctrnombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCctrnombre', array());

        return parent::getCctrnombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCctrvalor($cctrvalor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCctrvalor', array($cctrvalor));

        return parent::setCctrvalor($cctrvalor);
    }

    /**
     * {@inheritDoc}
     */
    public function getCctrvalor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCctrvalor', array());

        return parent::getCctrvalor();
    }

    /**
     * {@inheritDoc}
     */
    public function setNctrdescripcion($nctrdescripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNctrdescripcion', array($nctrdescripcion));

        return parent::setNctrdescripcion($nctrdescripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getNctrdescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNctrdescripcion', array());

        return parent::getNctrdescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setNctrestado($nctrestado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNctrestado', array($nctrestado));

        return parent::setNctrestado($nctrestado);
    }

    /**
     * {@inheritDoc}
     */
    public function getNctrestado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNctrestado', array());

        return parent::getNctrestado();
    }

    /**
     * {@inheritDoc}
     */
    public function setPadre(\Sistema\Entity\Control $padre = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPadre', array($padre));

        return parent::setPadre($padre);
    }

    /**
     * {@inheritDoc}
     */
    public function getPadre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPadre', array());

        return parent::getPadre();
    }

    /**
     * {@inheritDoc}
     */
    public function addHijo(\Sistema\Entity\Control $hijos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHijo', array($hijos));

        return parent::addHijo($hijos);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHijo(\Sistema\Entity\Control $hijos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHijo', array($hijos));

        return parent::removeHijo($hijos);
    }

    /**
     * {@inheritDoc}
     */
    public function getHijos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHijos', array());

        return parent::getHijos();
    }

    /**
     * {@inheritDoc}
     */
    public function addRolcontrol(\Sistema\Entity\Rolcontrol $rolcontrols)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRolcontrol', array($rolcontrols));

        return parent::addRolcontrol($rolcontrols);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRolcontrol(\Sistema\Entity\Rolcontrol $rolcontrols)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRolcontrol', array($rolcontrols));

        return parent::removeRolcontrol($rolcontrols);
    }

    /**
     * {@inheritDoc}
     */
    public function getRolcontrols()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRolcontrols', array());

        return parent::getRolcontrols();
    }

    /**
     * {@inheritDoc}
     */
    public function addPerusuacceso(\Sistema\Entity\Perusuacceso $perusuaccesos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPerusuacceso', array($perusuaccesos));

        return parent::addPerusuacceso($perusuaccesos);
    }

    /**
     * {@inheritDoc}
     */
    public function removePerusuacceso(\Sistema\Entity\Perusuacceso $perusuaccesos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePerusuacceso', array($perusuaccesos));

        return parent::removePerusuacceso($perusuaccesos);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerusuaccesos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerusuaccesos', array());

        return parent::getPerusuaccesos();
    }

}
