<?php

namespace DoctrineORMModule\Proxy\__CG__\Sistema\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Persona extends \Sistema\Entity\Persona implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Sistema\\Entity\\Persona' . "\0" . 'npercodigo', '' . "\0" . 'Sistema\\Entity\\Persona' . "\0" . 'cpernombre', '' . "\0" . 'Sistema\\Entity\\Persona' . "\0" . 'cperapellidos', '' . "\0" . 'Sistema\\Entity\\Persona' . "\0" . 'nperdni', '' . "\0" . 'Sistema\\Entity\\Persona' . "\0" . 'dpernacimiento', '' . "\0" . 'Sistema\\Entity\\Persona' . "\0" . 'npertipo', '' . "\0" . 'Sistema\\Entity\\Persona' . "\0" . 'nperestado', 'perusuarios');
        }

        return array('__isInitialized__', '' . "\0" . 'Sistema\\Entity\\Persona' . "\0" . 'npercodigo', '' . "\0" . 'Sistema\\Entity\\Persona' . "\0" . 'cpernombre', '' . "\0" . 'Sistema\\Entity\\Persona' . "\0" . 'cperapellidos', '' . "\0" . 'Sistema\\Entity\\Persona' . "\0" . 'nperdni', '' . "\0" . 'Sistema\\Entity\\Persona' . "\0" . 'dpernacimiento', '' . "\0" . 'Sistema\\Entity\\Persona' . "\0" . 'npertipo', '' . "\0" . 'Sistema\\Entity\\Persona' . "\0" . 'nperestado', 'perusuarios');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Persona $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getNpercodigo()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getNpercodigo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNpercodigo', array());

        return parent::getNpercodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpernombre($cpernombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpernombre', array($cpernombre));

        return parent::setCpernombre($cpernombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpernombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpernombre', array());

        return parent::getCpernombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCperapellidos($cperapellidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCperapellidos', array($cperapellidos));

        return parent::setCperapellidos($cperapellidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getCperapellidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCperapellidos', array());

        return parent::getCperapellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setNperdni($nperdni)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNperdni', array($nperdni));

        return parent::setNperdni($nperdni);
    }

    /**
     * {@inheritDoc}
     */
    public function getNperdni()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNperdni', array());

        return parent::getNperdni();
    }

    /**
     * {@inheritDoc}
     */
    public function setDpernacimiento($dpernacimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDpernacimiento', array($dpernacimiento));

        return parent::setDpernacimiento($dpernacimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDpernacimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDpernacimiento', array());

        return parent::getDpernacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setNpertipo($npertipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNpertipo', array($npertipo));

        return parent::setNpertipo($npertipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNpertipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNpertipo', array());

        return parent::getNpertipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNperestado($nperestado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNperestado', array($nperestado));

        return parent::setNperestado($nperestado);
    }

    /**
     * {@inheritDoc}
     */
    public function getNperestado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNperestado', array());

        return parent::getNperestado();
    }

    /**
     * {@inheritDoc}
     */
    public function addPerusuario(\Sistema\Entity\Perusuario $perusuarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPerusuario', array($perusuarios));

        return parent::addPerusuario($perusuarios);
    }

    /**
     * {@inheritDoc}
     */
    public function removePerusuario(\Sistema\Entity\Perusuario $perusuarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePerusuario', array($perusuarios));

        return parent::removePerusuario($perusuarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerusuarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerusuarios', array());

        return parent::getPerusuarios();
    }

}
