<?php

namespace DoctrineORMModule\Proxy\__CG__\Sistema\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Menu extends \Sistema\Entity\Menu implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Sistema\\Entity\\Menu' . "\0" . 'nmencodigo', '' . "\0" . 'Sistema\\Entity\\Menu' . "\0" . 'nmencodpadre', '' . "\0" . 'Sistema\\Entity\\Menu' . "\0" . 'cmenjerarquia', '' . "\0" . 'Sistema\\Entity\\Menu' . "\0" . 'cmennombre', '' . "\0" . 'Sistema\\Entity\\Menu' . "\0" . 'cmenvalor', '' . "\0" . 'Sistema\\Entity\\Menu' . "\0" . 'dmenfechapublico', '' . "\0" . 'Sistema\\Entity\\Menu' . "\0" . 'nmenestado', '' . "\0" . 'Sistema\\Entity\\Menu' . "\0" . 'padre', 'hijos', 'nivelmenu', 'tipocontenido', 'htmls', 'pdfs', 'urls');
        }

        return array('__isInitialized__', '' . "\0" . 'Sistema\\Entity\\Menu' . "\0" . 'nmencodigo', '' . "\0" . 'Sistema\\Entity\\Menu' . "\0" . 'nmencodpadre', '' . "\0" . 'Sistema\\Entity\\Menu' . "\0" . 'cmenjerarquia', '' . "\0" . 'Sistema\\Entity\\Menu' . "\0" . 'cmennombre', '' . "\0" . 'Sistema\\Entity\\Menu' . "\0" . 'cmenvalor', '' . "\0" . 'Sistema\\Entity\\Menu' . "\0" . 'dmenfechapublico', '' . "\0" . 'Sistema\\Entity\\Menu' . "\0" . 'nmenestado', '' . "\0" . 'Sistema\\Entity\\Menu' . "\0" . 'padre', 'hijos', 'nivelmenu', 'tipocontenido', 'htmls', 'pdfs', 'urls');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Menu $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getNmencodigo()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getNmencodigo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNmencodigo', array());

        return parent::getNmencodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNmencodpadre($nmencodpadre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNmencodpadre', array($nmencodpadre));

        return parent::setNmencodpadre($nmencodpadre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNmencodpadre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNmencodpadre', array());

        return parent::getNmencodpadre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCmenjerarquia($cmenjerarquia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCmenjerarquia', array($cmenjerarquia));

        return parent::setCmenjerarquia($cmenjerarquia);
    }

    /**
     * {@inheritDoc}
     */
    public function getCmenjerarquia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCmenjerarquia', array());

        return parent::getCmenjerarquia();
    }

    /**
     * {@inheritDoc}
     */
    public function setCmennombre($cmennombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCmennombre', array($cmennombre));

        return parent::setCmennombre($cmennombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getCmennombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCmennombre', array());

        return parent::getCmennombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCmenvalor($cmenvalor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCmenvalor', array($cmenvalor));

        return parent::setCmenvalor($cmenvalor);
    }

    /**
     * {@inheritDoc}
     */
    public function getCmenvalor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCmenvalor', array());

        return parent::getCmenvalor();
    }

    /**
     * {@inheritDoc}
     */
    public function setDmenfechapublico($dmenfechapublico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDmenfechapublico', array($dmenfechapublico));

        return parent::setDmenfechapublico($dmenfechapublico);
    }

    /**
     * {@inheritDoc}
     */
    public function getDmenfechapublico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDmenfechapublico', array());

        return parent::getDmenfechapublico();
    }

    /**
     * {@inheritDoc}
     */
    public function setNmenestado($nmenestado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNmenestado', array($nmenestado));

        return parent::setNmenestado($nmenestado);
    }

    /**
     * {@inheritDoc}
     */
    public function getNmenestado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNmenestado', array());

        return parent::getNmenestado();
    }

    /**
     * {@inheritDoc}
     */
    public function setPadre(\Sistema\Entity\Menu $padre = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPadre', array($padre));

        return parent::setPadre($padre);
    }

    /**
     * {@inheritDoc}
     */
    public function getPadre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPadre', array());

        return parent::getPadre();
    }

    /**
     * {@inheritDoc}
     */
    public function addHijo(\Sistema\Entity\Menu $hijos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHijo', array($hijos));

        return parent::addHijo($hijos);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHijo(\Sistema\Entity\Menu $hijos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHijo', array($hijos));

        return parent::removeHijo($hijos);
    }

    /**
     * {@inheritDoc}
     */
    public function getHijos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHijos', array());

        return parent::getHijos();
    }

    /**
     * {@inheritDoc}
     */
    public function setNivelmenu(\Sistema\Entity\Nivelmenu $nivelmenu = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNivelmenu', array($nivelmenu));

        return parent::setNivelmenu($nivelmenu);
    }

    /**
     * {@inheritDoc}
     */
    public function getNivelmenu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNivelmenu', array());

        return parent::getNivelmenu();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipocontenido(\Sistema\Entity\Tipocontenido $tipocontenido = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipocontenido', array($tipocontenido));

        return parent::setTipocontenido($tipocontenido);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipocontenido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipocontenido', array());

        return parent::getTipocontenido();
    }

    /**
     * {@inheritDoc}
     */
    public function addHtml(\Sistema\Entity\Html $htmls)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHtml', array($htmls));

        return parent::addHtml($htmls);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHtml(\Sistema\Entity\Html $htmls)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHtml', array($htmls));

        return parent::removeHtml($htmls);
    }

    /**
     * {@inheritDoc}
     */
    public function getHtmls()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHtmls', array());

        return parent::getHtmls();
    }

    /**
     * {@inheritDoc}
     */
    public function addPdf(\Sistema\Entity\Pdf $pdfs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPdf', array($pdfs));

        return parent::addPdf($pdfs);
    }

    /**
     * {@inheritDoc}
     */
    public function removePdf(\Sistema\Entity\Pdf $pdfs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePdf', array($pdfs));

        return parent::removePdf($pdfs);
    }

    /**
     * {@inheritDoc}
     */
    public function getPdfs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPdfs', array());

        return parent::getPdfs();
    }

    /**
     * {@inheritDoc}
     */
    public function addUrl(\Sistema\Entity\Url $urls)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUrl', array($urls));

        return parent::addUrl($urls);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUrl(\Sistema\Entity\Url $urls)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUrl', array($urls));

        return parent::removeUrl($urls);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrls()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrls', array());

        return parent::getUrls();
    }

}
