<?php $this->placeholder('contenido')->captureStart(); ?>
<div class="cont-noticia">
	<div class="sidebar">
		<?php echo $this->partial('portal/sidebar.phtml') ?>
	</div>
	<div class="detalle">
		<h1 class="titulo-con-logo"><i class="fa fa-volume-up"></i><span>AMPLIACIÓN DE NOTICIA</span></h1>
		<div class="ck-contenido">
			<?php echo $detalle ?>
		</div>
		<div class="fb-comments" data-href="http://ot.regionlambayeque.gob.pe/" data-numposts="5" data-colorscheme="light"></div>
	</div>
</div>
<?php $this->placeholder('contenido')->captureEnd(); ?>