<?php $this->placeholder('contenido')->captureStart(); ?>
<div class="cont-noticia">
	<div class="sidebar">
		<?php echo $this->partial('portal/sidebar.phtml') ?>
	</div>
	<div class="lista">
		<h1 class="titulo-con-logo"><i class="fa fa-volume-up"></i><span>NOTICIAS</span></h1>
		<ul class="noticias">
			<?php
			foreach ($this->noticias as $noticia) {
				$href = $this->url('portal/noticia', array('codigo' => $noticia->getNnotcodigo()));
				?>
				<li>
					<div class="noticia">
						<a href="<?php echo $href ?>">
							<img src="<?php echo $this->htImgUrl($noticia->getCnotrutaimgfull(), 'estandar') ?>" alt="" class="miniatura">
						</a>
						<div class="texto">
							<a href="<?php echo $href ?>"><h1 class="titulo"><?php echo $noticia->getCnottitulo() ?></h1></a>
							<p><?php echo $noticia->getCnotpietitulo() ?></p>
						</div>
					</div>
				</li>
				<?php
			}
			?>
		</ul>
		<?php echo $this->paginationControl($paginador, 'Sliding', 'portal\paginador', array('ruta' => $this->ruta)); ?>
	</div>
</div>
<?php $this->placeholder('contenido')->captureEnd(); ?>