<div class="componente" data-componente="modal" data-modal-nombre="modal-post" data-modal-width="500" data-modal-title="Editar">
	<div class="marco">
		<div class="componente" data-componente="formulario" data-formulario-nombre="formulario">
			<?php
			$form = $this->form;
			$form->setAttribute('data-ruta', $this->url($this->ruta, array('action' => 'editar', 'parametros' => $this->id)));

			echo $this->form()->openTag($form);
			?>
			<div class="modal-body">
				<?php
				$layoutHorizontal = TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL;

				// cimagaltitulo
				$input = $form->get('cimagaltitulo');
				$input->setOptions(array(
					'column-size' => 'lg-9',
					'label_attributes' => array(
						'class' => 'col-lg-3',
						),
					'twb-layout' => $layoutHorizontal,
					));
				echo $this->formRow($input);

				// cimagalimg
				$cimagalimg = $form->get('cimagalimg');
				$cimagalimg->setOptions(array(
					'label_attributes' => array(
						'class' => 'col-lg-3 control-label',
						),
					)
				);
				$value = $cimagalimg->getAttribute('data-value');
				$cimagalimgPath = ($value != '') ? $this->htImgUrl($cimagalimg->getAttribute('data-value'), 'estandar') : '';
				$cimagalimg->setAttribute('data-path', $cimagalimgPath);

				// imgString
				$imgString = $form->get('imgString');
				$imgString->setOptions(array(
					'label_attributes' => array(
						'class' => 'col-lg-3',
						),
					)
				);
				?>
				<div class="form-group file-group">
					<?php echo $this->formLabel($cimagalimg) ?>
					<div class="col-lg-9">
						<?php echo $this->formElement($cimagalimg) ?>
						<?php echo $this->formElement($imgString) ?>
					</div>
				</div>
				<?php
				// galeria
				$input = $form->get('galeria');
				$input->setOptions(array(
					'column-size' => 'lg-9',
					'label_attributes' => array(
						'class' => 'col-lg-3',
						),
					'twb-layout' => $layoutHorizontal,
					));
				echo $this->formRow($input);
				?>
				<div class="modal-footer">
					<button type="button" class="btn btn-default btn-modal cancelar" data-dismiss="modal">Cancelar</button>
					<?php
					// enviar
					$button = $form->get('enviar');
					$button->setOptions(array(
						'column-size' => 'sm-10 col-sm-offset-2',
						));
					echo $this->formButton($button);
					?>
				</div>
			</div>
			<?php echo $this->form()->closeTag($form); ?>
		</div>
	</div>
</div>