<div class="componente" data-componente="modal" data-modal-nombre="modal-post" data-modal-width="550" data-modal-title="Registrar">
	<div class="marco">
		<div class="componente" data-componente="formulario" data-formulario-nombre="formulario">
			<?php
			$form = $this->form;
			$form->setAttribute('data-ruta', $this->url($this->ruta, array('action' => 'agregar')));

			echo $this->form()->openTag($form);
			?>
			<div class="modal-body">
				<?php
				$layoutHorizontal = TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL;

				// cgaltitulo
				$input = $form->get('cgaltitulo');
				$input->setOptions(array(
					'column-size' => 'lg-9',
					'label_attributes' => array(
						'class' => 'col-lg-3',
						),
					'twb-layout' => $layoutHorizontal,
					));
				echo $this->formRow($input);

				// cgalsubtitulo
				$input = $form->get('cgalsubtitulo');
				$input->setOptions(array(
					'column-size' => 'lg-9',
					'label_attributes' => array(
						'class' => 'col-lg-3',
						),
					'twb-layout' => $layoutHorizontal,
					));
				echo $this->formRow($input);

				// cgalimagen
				$cgalimagen = $form->get('cgalimagen');
				$cgalimagen->setOptions(array(
					'label_attributes' => array(
						'class' => 'col-lg-3 control-label',
						),
					)
				);
				$value = $cgalimagen->getAttribute('data-value');
				$cgalimagenPath = ($value != '') ? $this->htImgUrl($cgalimagen->getAttribute('data-value'), 'estandar') : '';
				$cgalimagen->setAttribute('data-path', $cgalimagenPath);

				// imgString
				$imgString = $form->get('imgString');
				$imgString->setOptions(array(
					'label_attributes' => array(
						'class' => 'col-lg-3',
						),
					)
				);
				?>
				<div class="form-group file-group">
					<?php echo $this->formLabel($cgalimagen) ?>
					<div class="col-lg-9">
						<?php echo $this->formElement($cgalimagen) ?>
						<?php echo $this->formElement($imgString) ?>
					</div>
				</div>
				<?php

				// dgalfecha
				$input = $form->get('dgalfecha');
				$input->setOptions(array(
					'column-size' => 'lg-4',
					'label_attributes' => array(
						'class' => 'col-lg-3',
						),
					'twb-layout' => $layoutHorizontal,
					));
				echo $this->formRow($input);

				// padre
				$input = $form->get('padre');
				$input->setOptions(array(
					'column-size' => 'lg-9',
					'label_attributes' => array(
						'class' => 'col-lg-3',
						),
					'twb-layout' => $layoutHorizontal,
					));
				echo $this->formRow($input);
				?>
				<div class="modal-footer">
					<button type="button" class="btn btn-default btn-modal cancelar" data-dismiss="modal">Cancelar</button>
					<?php
					// enviar
					$button = $form->get('enviar');
					$button->setOptions(array(
						'column-size' => 'sm-10 col-sm-offset-2',
						));
					echo $this->formButton($button);
					?>
				</div>
			</div>
			<?php echo $this->form()->closeTag($form); ?>
		</div>
	</div>
</div>