<div class="componente" data-componente="modal" data-modal-nombre="modal-post" data-modal-width="550" data-modal-title="Editar">
	<div class="marco">
		<div class="componente" data-componente="formulario" data-formulario-nombre="formulario">
			<?php
			$form = $this->form;
			$form->setAttribute('data-ruta', $this->url($this->ruta, array('action' => 'editar', 'parametros' => $this->id)));

			echo $this->form()->openTag($form);
			?>
			<div class="modal-body">
				<?php
				$layoutHorizontal = TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL;

				// cpubtitulo
				$input = $form->get('cpubtitulo');
				$input->setOptions(array(
					'column-size' => 'lg-9',
					'label_attributes' => array(
						'class' => 'col-lg-3',
						),
					'twb-layout' => $layoutHorizontal,
					));
				echo $this->formRow($input);

				// cpubanio
				$input = $form->get('cpubanio');
				$input->setOptions(array(
					'column-size' => 'lg-4',
					'label_attributes' => array(
						'class' => 'col-lg-3',
						),
					'twb-layout' => $layoutHorizontal,
					));
				echo $this->formRow($input);

				// cpubimagen
				$cpubimagen = $form->get('cpubimagen');
				$cpubimagen->setOptions(array(
					'label_attributes' => array(
						'class' => 'col-lg-3 control-label',
						),
					)
				);
				$value = $cpubimagen->getAttribute('data-value');
				$cpubimagenPath = ($value != '') ? $this->htImgUrl($cpubimagen->getAttribute('data-value'), 'estandar') : '';
				$cpubimagen->setAttribute('data-path', $cpubimagenPath);

				// imgString
				$imgString = $form->get('imgString');
				$imgString->setOptions(array(
					'label_attributes' => array(
						'class' => 'col-lg-3',
						),
					)
				);
				?>
				<div class="form-group file-group">
					<?php echo $this->formLabel($cpubimagen) ?>
					<div class="col-lg-9">
						<?php echo $this->formElement($cpubimagen) ?>
						<?php echo $this->formElement($imgString) ?>
					</div>
				</div>
				<?php
				// cpubpdf
				$cpubpdf = $form->get('cpubpdf');
				$cpubpdf->setOptions(array(
					'label_attributes' => array(
						'class' => 'col-lg-3 control-label',
						),
					)
				);

				// pdfString
				$pdfString = $form->get('pdfString');
				$pdfString->setOptions(array(
					'label_attributes' => array(
						'class' => 'col-lg-3',
						),
					)
				);
				?>
				<div class="form-group file-group">
					<?php echo $this->formLabel($cpubpdf) ?>
					<div class="col-lg-9">
						<?php echo $this->formElement($cpubpdf) ?>
						<?php echo $this->formElement($pdfString) ?>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default btn-modal cancelar" data-dismiss="modal">Cancelar</button>
					<?php
					// enviar
					$button = $form->get('enviar');
					$button->setOptions(array(
						'column-size' => 'sm-10 col-sm-offset-2',
						));
					echo $this->formButton($button);
					?>
				</div>
			</div>
			<?php echo $this->form()->closeTag($form); ?>
		</div>
	</div>
</div>