<div class="componente" data-componente="modal" data-modal-nombre="modal-post" data-modal-title="Registrar" data-modal-width="500">
	<div class="marco">
		<div class="componente" data-componente="formulario" data-formulario-nombre="formulario">
			<?php
			$form = $this->form;
			$form->setAttribute('data-ruta', $this->url($this->ruta, array('action' => 'agregar')));

			echo $this->form()->openTag($form);
			?>
			<div class="modal-body">
				<?php
				$layoutHorizontal = TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL;

        			// cpernombre
				$input = $form->get('cpernombre');
				$input->setAttributes(array(
					'data-bv-notempty'=> '',
					));
				$input->setOptions(array(
					'label' => 'Nombre',
					'column-size' => 'lg-9',
					'label_attributes' => array(
						'class' => 'col-lg-3',
						),
					'twb-layout' => $layoutHorizontal,
					));
				echo $this->formRow($input);

        			// cperapellidos
				$input = $form->get('cperapellidos');
				$input->setOptions(array(
					'label' => 'Apellidos',
					'column-size' => 'lg-9',
					'label_attributes' => array(
						'class' => 'col-lg-3',
						),
					'twb-layout' => $layoutHorizontal,
					));
				echo $this->formRow($input);

        			// nperdni
				$input = $form->get('nperdni');
				$input->setOptions(array(
					'label' => 'DNI',
					'column-size' => 'lg-4',
					'label_attributes' => array(
						'class' => 'col-lg-3',
						),
					'twb-layout' => $layoutHorizontal,
					));
				echo $this->formRow($input);

        			// dpernacimiento
				$input = $form->get('dpernacimiento');
				$input->setAttributes(array(
					'type' => 'text',
					'data-provide' => 'datepicker',
					'data-date-format' => 'dd-mm-yyyy',
					));
				$input->setOptions(array(
					'label' => 'F. de nac.',
					'column-size' => 'lg-4',
					'label_attributes' => array(
						'class' => 'col-lg-3',
						),
					'twb-layout' => $layoutHorizontal,
					));
				echo $this->formRow($input);
				?>
				<div class="modal-footer">
					<button type="button" class="btn btn-default btn-modal cancelar">Cancelar</button>
					<?php
          				// enviar
					$button = $form->get('enviar');
					$button->setOptions(array(
						'label' => 'Guardar',
						'column-size' => 'sm-10 col-sm-offset-2',
						));
					$button->setAttributes(array(
						'type' => 'submit',
						'class' => 'btn btn-modal enviar',
						));
					echo $this->formButton($button);
					?>
				</div>
			</div>
			<?php echo $this->form()->closeTag($form); ?>
		</div>
	</div>
</div>