<div class="componente" data-componente="mantenedor" data-mantenedor-nombre="mantenedor">
	<div class="dialog post"></div>
	<?php echo $this->partial('sistema/plantillas/alerta-modal.phtml', array('personas' => $this->personas)) ?>
	<div class="row navegador">
		<div class="col-lg-12">
			<ul>
				<li><a href="" class="resaltado">Inicio</a></li>
				<li class="separador">></li>
				<li>Roles</li>
			</ul>
		</div>
	</div>
	<div class="marco-data">
		<div class="row botonera">
			<div class="col-lg-12">
				<?php
				echo $this->partial('sistema/botonera.phtml', array(
					'botones' => $this->botones,
					'rutaRaiz' => $this->rutaRaiz,
					)
				);
				?>
			</div>
		</div>
		<div class="componente" data-componente="tabla-mantenedor" data-tabla-mantenedor-nombre="tabla-mantenedor" data-ruta="<?php echo $this->rutaFiltrar ?>">
			<div class="row data">
				<div class="col-lg-12">
					<div class="row tabla">
						<div class="col-lg-12">
							<div class="cnt-tabla">
								<table class="table table-striped">
									<tr class="opciones">
										<td class="icono"><span class="glyphicon glyphicon-th"></span></td>
										<td>
											<h1 class="titulo">Lista de roles</h1>
										</td>
										<td>
											<!-- Selector -->
											<select class="selectpicker" name="selector-items" data-width="100px">
												<?php foreach ($this->opcionesItems as $opcion): ?>
													<?php if ($opcion['selected']): ?>
														<option value="<?php echo $opcion['value'] ?>" selected="selected">
															<?php echo $opcion['label'] ?>
														</option>
													<?php else: ?>
														<option value="<?php echo $opcion['value'] ?>">
															<?php echo $opcion['label'] ?>
														</option>
													<?php endif ?>
												<?php endforeach ?>
											</select>
										</td>
									</tr>
									<tr class="campos-busqueda">
										<td></td>
										<td><input class="form-control" type="text" name="crolnombre" id="" placeholder="Nombre" autocomplete="off"></td>
										<td><input class="form-control" type="text" name="croldescripcion" id="" placeholder="Descripcion" autocomplete="off"></td>
									</tr>
									<tr></tr>
									<tr class="cabecera">
										<th></th>
										<th>Nombre</th>
										<th>Descripcion</th>
									</tr>
									<?php echo $this->partial('sistema/rol/tabla.phtml', array('rols' => $this->rols)) ?>
								</table>
							</div>
						</div>
					</div>
					<div class="row paginador">
						<div class="col-lg-12 text-center">
							<?php echo $this->partial('sistema/paginador.phtml', array('paginador' => $this->paginador, 'ruta' => $this->ruta)) ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
