<div class="componente" data-componente="modal" data-modal-nombre="modal-post" data-modal-width="400" data-modal-title="Error">
	<div class="marco">
		<div class="componente" data-componente="formulario" data-formulario-nombre="formulario">
			<div class="modal-body">
				<div class="alert alert-warning" role="alert">
				<?php echo $this->error ?>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default btn-modal aceptar" data-dismiss="modal">Aceptar</button>
				</div>
			</div>
		</div>
	</div>
</div>