<div class="dialog pre alerta">
	<div class="componente" data-componente="modal" data-modal-nombre="modal-pre" data-modal-width="400" data-modal-title="Error">
		<div class="marco">
			<div class="modal-body">
				<div id="alerta-seleccion" class="alert alert-warning mensaje" role="alert"></div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default btn-modal aceptar" data-dismiss="modal">Aceptar</button>
				</div>
			</div>
		</div>
	</div>
</div>