<?php
$index = 0;
foreach ($rols as $key => $rol) {
	?>
	<tr class="item" data-id="<?php echo $rol->getNrolcodigo() ?>">
		<td>
			<label class="my-radio">
				<input type="radio" name="selector" id="">
				<i class="fa fa-circle-thin"></i>
				<i class="fa fa-dot-circle-o"></i>
			</label>
		</td>
		<td><?php echo $rol->getCrolnombre() ?></td>
		<td><?php echo $rol->getCroldescripcion() ?></td>
	</tr>
	<?php
}
?>