<div class="componente" data-componente="mantenedor" data-mantenedor-nombre="mantenedor">
	<div class="dialog post"></div>
	<?php echo $this->partial('sistema/plantillas/alerta-modal.phtml', array('videos' => $this->videos)) ?>
	<div class="row navegador">
		<div class="col-lg-12">
			<ul>
				<li><a href="" class="resaltado">Inicio</a></li>
				<li class="separador">></li>
				<li>Videos</li>
			</ul>
		</div>
	</div>
	<div class="marco-data">
		<div class="row botonera">
			<div class="col-lg-12">
				<?php
				echo $this->partial('sistema/botonera.phtml', array(
					'botones' => $this->botones,
					'rutaRaiz' => $this->rutaRaiz,
					)
				);
				?>
			</div>
		</div>
		<div class="componente" data-componente="tabla-mantenedor" data-tabla-mantenedor-nombre="tabla-mantenedor" data-ruta="<?php echo $this->rutaFiltrar ?>">
			<div class="row data">
				<div class="col-lg-12">
					<div class="row tabla">
						<div class="col-lg-12">
							<div class="cnt-tabla">
								<table class="table table-striped tabla-items" data-ruta-orden="<?php echo $this->url($this->ruta, array('action' => 'ordenar', 'parametros' => ':parametros')) ?>">
									<tr class="opciones">
										<td class="icono"><span class="glyphicon glyphicon-th"></span></td>
										<td colspan="3">
											<h1 class="titulo">Lista de videos</h1>
										</td>
										<td>
											<!-- Selector -->
											<form class="form-inline pull-right" role="form">
												<select class="form-control" name="selector-items" data-width="100px">
													<?php foreach ($this->opcionesItems as $opcion): ?>
														<?php if ($opcion['selected']): ?>
															<option value="<?php echo $opcion['value'] ?>" selected="selected">
																<?php echo $opcion['label'] ?>
															</option>
														<?php else: ?>
															<option value="<?php echo $opcion['value'] ?>">
																<?php echo $opcion['label'] ?>
															</option>
														<?php endif ?>
													<?php endforeach ?>
												</select>
											</form>
										</td>
									</tr>
									<tr class="campos-busqueda">
										<td></td>
										<td><input class="form-control" type="text" name="v.cvidtitulo" id="" placeholder="Título" autocomplete="off"></td>
										<td></td>
										<td></td>
										<td></td>
									</tr>
									<tr></tr>
									<tr class="cabecera">
										<th></th>
										<th>Título</th>
										<th>Fecha de publicación</th>
										<th>Estado</th>
										<th></th>
									</tr>
									<?php echo $this->partial('sistema/video/tabla.phtml', array('videos' => $this->videos)) ?>
								</table>
							</div>
						</div>
					</div>
					<div class="row paginador">
						<div class="col-lg-12 text-center">
							<?php echo $this->partial('sistema/paginador.phtml', array('paginador' => $this->paginador, 'ruta' => $this->ruta)) ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>