<div class="componente" data-componente="modal" data-modal-nombre="modal-post" data-modal-width="500" data-modal-title="Registrar">
	<div class="marco">
		<div class="componente" data-componente="formulario" data-formulario-nombre="formulario">
			<?php
			$form = $this->form;
			$form->setAttribute('data-ruta', $this->url($this->ruta, array('action' => 'agregar')));

			echo $this->form()->openTag($form);
			?>
			<div class="modal-body">
				<?php
				$layoutHorizontal = TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL;

				// cmennombre
				$input = $form->get('cmennombre');
				$input->setOptions(array(
					'column-size' => 'lg-8',
					'label_attributes' => array(
						'class' => 'col-lg-4',
						),
					'twb-layout' => $layoutHorizontal,
					));
				echo $this->formRow($input);

				// nivelmenu
				$input = $form->get('nivelmenu');
				$input->setOptions(array(
					'column-size' => 'lg-8',
					'label_attributes' => array(
						'class' => 'col-lg-4',
						),
					'twb-layout' => $layoutHorizontal,
					));
				echo $this->formRow($input);

				// tipocontenido
				$input = $form->get('tipocontenido');
				$input->setOptions(array(
					'column-size' => 'lg-8',
					'label_attributes' => array(
						'class' => 'col-lg-4',
						),
					'twb-layout' => $layoutHorizontal,
					));
				echo $this->formRow($input);

				// padre
				$input = $form->get('padre');
				$input->setOptions(array(
					'column-size' => 'lg-8',
					'label_attributes' => array(
						'class' => 'col-lg-4',
						),
					'twb-layout' => $layoutHorizontal,
					));
				echo $this->formRow($input);
				?>
				<div class="modal-footer">
					<button type="button" class="btn btn-default btn-modal cancelar" data-dismiss="modal">Cancelar</button>
					<?php
					// enviar
					$button = $form->get('enviar');
					$button->setOptions(array(
						'column-size' => 'sm-10 col-sm-offset-2',
						));
					echo $this->formButton($button);
					?>
				</div>
			</div>
			<?php echo $this->form()->closeTag($form); ?>
		</div>
	</div>
</div>