<div class="componente" data-componente="modal" data-modal-nombre="modal-post" data-modal-width="500" data-modal-title="Contenido">
	<div class="marco">
		<div class="componente" data-componente="formulario" data-formulario-nombre="formulario">
			<?php
			$form = $this->form;
			$form->setAttribute('data-ruta', $this->url($this->ruta, array('action' => 'contenido', 'parametros' => $this->id)));

			echo $this->form()->openTag($form);
			?>
			<div class="modal-body">
				<?php
				$layoutHorizontal = TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL;

				// cpdf
				$cpdf = $form->get('cpdf');
				$cpdf->setOptions(array(
					'label_attributes' => array(
						'class' => 'col-lg-3 control-label',
						),
					)
				);

				// pdfString
				$pdfString = $form->get('pdfString');
				$pdfString->setOptions(array(
					'label_attributes' => array(
						'class' => 'col-lg-3',
						),
					)
				);
				?>
				<div class="form-group file-group">
					<?php echo $this->formLabel($cpdf) ?>
					<div class="col-lg-9">
						<?php echo $this->formElement($cpdf) ?>
						<?php echo $this->formElement($pdfString) ?>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default btn-modal cancelar" data-dismiss="modal">Cancelar</button>
					<?php
					// enviar
					$button = $form->get('enviar');
					$button->setOptions(array(
						'column-size' => 'sm-10 col-sm-offset-2',
						));
					echo $this->formButton($button);
					?>
				</div>
			</div>
			<?php echo $this->form()->closeTag($form); ?>
		</div>
	</div>
</div>