<?php

namespace Sistema\Repository;

use DoctrineORMModule\Paginator\Adapter\DoctrinePaginator as DoctrineAdapter;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator as ORMPaginator;
use Zend\Paginator\Paginator;

/**
 * GaleriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GaleriaRepository extends EntityRepository {
	public function addFiltro($qb, $campos, $paginacion) {
		$expr = $qb->expr();
		$andX = $expr->andX();

		foreach ($campos as $columna => $valor) {
			if (strpos($columna, '-') !== false) {
				$colSeparadas = explode('-', $columna);

				$orX = $qb->expr()->orX();
				for ($i = 0; $i < count($colSeparadas); $i++) {
					$parametro = substr($colSeparadas[$i], strpos($colSeparadas[$i], '.') + 1);
					$orX->add($expr->like($colSeparadas[$i], ':' . $parametro));
					$qb->setParameter($parametro, '%' . $valor . '%');

					switch (true) {
						case ($i === 0):
							$concat = $qb->expr()->concat($colSeparadas[$i], $qb->expr()->literal(' '));
							break;
						case ($i < count($colSeparadas) - 1):
							$concat = $qb->expr()->concat($concat, $qb->expr()->concat($colSeparadas[$i], $qb->expr()->literal(' ')));
							break;
						case ($i === count($colSeparadas) - 1):
							$concat = $qb->expr()->concat($concat, $colSeparadas[$i]);
							break;
					}
				}

				$orX->add($expr->like($concat, ':concat'));
				$qb->setParameter('concat', '%' . $valor . '%');
				$andX->add($orX);
			} else {
				$parametro = substr($columna, strpos($columna, '.') + 1);
				$andX->add($expr->like($columna, ':' . $parametro));
				$qb->setParameter($parametro, '%' . $valor . '%');
			}

		}
		$qb->andWhere($andX);

		if ($paginacion) {
			$qb->setFirstResult($paginacion['inicio']);
			$qb->setMaxResults($paginacion['items']);
		}

		$query = $qb->getQuery();
		return $query;
	}

	public function buscar($campos, $paginacion) {
		$qb = $this->_em->createQueryBuilder();
		$qb->select('g')
		   ->from('Sistema\Entity\Galeria', 'g')
		   ->where('g.ngalestado != :ngalestado')
		   ->orderBy('g.cgaljerarquia', 'ASC')
		   ->setParameter('ngalestado', 0);

		return $this->addFiltro($qb, $campos, $paginacion)->getResult();
	}

	public function getPaginador($campos, $paginacion) {
		$qb = $this->_em->createQueryBuilder();
		$qb->select('g')
		   ->from('Sistema\Entity\Galeria', 'g')
		   ->where('g.ngalestado != :ngalestado')
		   ->orderBy('g.cgaljerarquia', 'ASC')
		   ->setParameter('ngalestado', 0);

		$query = $this->addFiltro($qb, $campos, $paginacion);

		$adapter = new DoctrineAdapter(new ORMPaginator($query));
		$paginator = new Paginator($adapter);
		$paginator->setDefaultItemCountPerPage($paginacion['items']);
		$paginator->setCurrentPageNumber($paginacion['pagina']);

		return $paginator;
	}

	public function buscarUltimoOrden() {
		$qb = $this->_em->createQueryBuilder();
		$qb->select('g.cgaljerarquia')
		   ->from('Sistema\Entity\Galeria', 'g')
		   ->orderBy('g.cgaljerarquia', 'DESC')
		   ->setFirstResult(0)
		   ->setMaxResults(1);

		$query = $qb->getQuery();
		$tempResult = $query->getResult();
		if (!empty($tempResult)) {
			$result = $query->getSingleScalarResult();
		} else {
			$result = 0;
		}

		return $result;
	}

	public function buscarMenoresParaOrdenar($cgaljerarquiaMay, $cgaljerarquiaMin) {
		$qb = $this->_em->createQueryBuilder();
		$qb->select('g')
		   ->from('Sistema\Entity\Galeria', 'g')
		   ->where('g.cgaljerarquia > :cgaljerarquiaMin')
		   ->andWhere('g.cgaljerarquia <= :cgaljerarquiaMay')
		   ->setParameter('cgaljerarquiaMay', $cgaljerarquiaMay)
		   ->setParameter('cgaljerarquiaMin', $cgaljerarquiaMin);

		$query = $qb->getQuery();
		return $query->getResult();
	}

	public function buscarMayoresParaOrdenar($cgaljerarquiaMin, $cgaljerarquiaMay) {
		$qb = $this->_em->createQueryBuilder();
		$qb->select('g')
		   ->from('Sistema\Entity\Galeria', 'g')
		   ->where('g.cgaljerarquia >= :cgaljerarquiaMin')
		   ->andWhere('g.cgaljerarquia < :cgaljerarquiaMay')
		   ->setParameter('cgaljerarquiaMin', $cgaljerarquiaMin)
		   ->setParameter('cgaljerarquiaMay', $cgaljerarquiaMay);

		$query = $qb->getQuery();
		return $query->getResult();
	}

	public function buscarHabilitados($ngalcodigo = null) {
		$qb = $this->_em->createQueryBuilder();
		$qb->select('g')
		   ->from('Sistema\Entity\Galeria', 'g')
		   ->where('g.ngalestado != :ngalestado')
		   ->orderBy('g.cgaltitulo', 'ASC')
		   ->setParameter('ngalestado', 0);

		if ($ngalcodigo) {
			$qb->andWhere('g.ngalcodigo != :ngalcodigo')
			   ->setParameter('ngalcodigo', $ngalcodigo);
		}

		$query = $qb->getQuery();
		return $query->getResult();
	}
}
