<?php

namespace Sistema\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RolcontrolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolcontrolRepository extends EntityRepository {
	public function buscarPorpk($nrolcodigo, $nctrcodigo) {
		$qb = $this->_em->createQueryBuilder();

		$qb->select('rc')
		   ->from('Sistema\Entity\Rolcontrol', 'rc')
		   ->innerJoin('rc.rol', 'r')
		   ->innerJoin('rc.control', 'c')
		   ->where('r = :nrolcodigo')
		   ->andWhere('c = :nctrcodigo')
		   ->setParameter('nrolcodigo', $nrolcodigo)
		   ->setParameter('nctrcodigo', $nctrcodigo);

		$query = $qb->getQuery();
		return $query->getOneOrNullResult();
	}

	public function buscarPorRol($nrolcodigo) {
		$qb = $this->_em->createQueryBuilder();

		$qb->select('rc')
		   ->from('Sistema\Entity\Rolcontrol', 'rc')
		   ->where('rc.rol = :nrolcodigo')
		   ->setParameter('nrolcodigo', $nrolcodigo);

		$query = $qb->getQuery();
		return $query->getResult();
	}
}
