<ul class="lista-items" data-ruta-orden="<?php echo $this->url($this->ruta, array('action' => 'ordenar', 'parametros' => ':parametros')) ?>">
	<?php
	$index = 0;
	foreach ($boletins as $key => $boletin) {
		?>
		<li class="item" data-id="<?php echo $boletin->getNbolcodigo() ?>">
			<?php
			$cboltitulo = $boletin->getCboltitulo();
			$cbolrutaimg = $boletin->getCbolrutaimg();
			$dbolfechareg = $boletin->getDbolfechareg()->format('d-m-Y');
			$cbolrutapdf = $boletin->getCbolrutapdf();
			$nbolestado = $boletin->getNbolestado();
			?>
			<label class="my-radio">
				<input type="radio" name="selector">
				<i class="fa fa-circle-thin"></i>
				<i class="fa fa-dot-circle-o"></i>
				<div class="titulo"><?php echo $cboltitulo ?></div>
			</label>
			<?php if ($cbolrutaimg != ''): ?>
				<div class="campo-img">
					<img src="<?php echo $this->htImgUrl($cbolrutaimg, 'estandar') ?>" alt="">
				</div>
			<?php endif ?>
			<hr>
			<?php if ($dbolfechareg != ''): ?>
				<div class="campo-compuesto">
					<i class="fa fa-calendar"></i>
					<div class="texto">
						<?php echo $dbolfechareg ?>
					</div>
				</div>
			<?php endif ?>
			<?php if ($cbolrutapdf != ''): ?>
				<div class="campo-compuesto">
					<i class="fa fa-external-link"></i>
					<a target="_blank" href="<?php echo $this->basePath().'/upload/pdf/'.$cbolrutapdf ?>">Ver</a>
				</div>
			<?php endif ?>
			<?php if ($nbolestado == 1): ?>
				<div class="campo-compuesto">
					<i class="fa fa-unlock"></i>
					<div class="texto">No publicado</div>
				</div>
			<?php elseif($nbolestado == 2): ?>
				<div class="campo-compuesto">
					<i class="fa fa-unlock-alt"></i>
					<div class="texto">Publicado</div>
				</div>
			<?php endif ?>
		</li>
		<?php
	}
	?>
</ul>