<ul class="lista-items">
	<?php
	$index = 0;
	foreach ($tipocontenidos as $key => $tipocontenido) {
		?>
		<li class="item" data-id="<?php echo $tipocontenido->getNtipconcodigo() ?>">
			<?php
			$ctipconnombre = $tipocontenido->getCtipconnombre();
			$ctipcondescripcion = $tipocontenido->getCtipcondescripcion();
			?>
			<label class="my-radio">
				<input type="radio" name="selector">
				<i class="fa fa-circle-thin"></i>
				<i class="fa fa-dot-circle-o"></i>
				<div class="titulo"><?php echo $ctipconnombre ?></div>
			</label>
			<div class="campo-icono">
				<i class="fa fa-file-image-o"></i>
			</div>
			<hr>
			<?php if ($ctipcondescripcion != ''): ?>
				<div class="campo-compuesto">
					<i class="fa fa-file-text-o"></i>
					<div class="texto">
						<?php echo $ctipcondescripcion ?>
					</div>
				</div>
			<?php endif ?>
		</li>
		<?php
	}
	?>
</ul>