<?php

namespace Sistema\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ControlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControlRepository extends EntityRepository {
	public function buscarPorUsuario($nperusucodigo) {
		$qb = $this->_em->createQueryBuilder();
		$qb2 = $this->_em->createQueryBuilder();
		$qb3 = $this->_em->createQueryBuilder();
		$qb4 = $this->_em->createQueryBuilder();

		$dql2 = $qb2->select('COUNT(pu2)')
		            ->from('Sistema\Entity\Perusuario', 'pu2')
		            ->innerJoin('pu2.perusuaccesos', 'pua2')
		            ->innerJoin('pua2.control', 'c2')
		            ->where('pu2.nperusucodigo = :nperusucodigo')
		            ->andWhere('pua2.nperusuaccestado = :nperusuaccestado2')
		            ->andWhere('c2.nctrcodigo = c.nctrcodigo')
		            ->getDQL();

		$dql3 = $qb3->select('COUNT(pu3)')
		            ->from('Sistema\Entity\Perusuario', 'pu3')
		            ->innerJoin('pu3.rol', 'r3')
		            ->innerJoin('r3.rolcontrols', 'rc3')
		            ->innerJoin('rc3.control', 'c3')
		            ->where('pu3.nperusucodigo = :nperusucodigo')
		            ->andWhere('rc3.nrolctrestado = :nrolctrestado3')
		            ->andWhere('c3.nctrcodigo = c.nctrcodigo')
		            ->getDQL();

		$dql4 = $qb4->select('COUNT(pu4)')
		            ->from('Sistema\Entity\Perusuario', 'pu4')
		            ->innerJoin('pu4.perusuaccesos', 'pua4')
		            ->innerJoin('pua4.control', 'c4')
		            ->where('pu4.nperusucodigo = :nperusucodigo')
		            ->andWhere('pua4.nperusuaccestado = :nperusuaccestado4')
		            ->andWhere('c4.nctrcodigo = c.nctrcodigo')
		            ->getDQL();

		$qb->select('c')
		   ->from('Sistema\Entity\Control', 'c')
		   ->where('c.nctrestado = :nctrestado')
		   ->andWhere('(' . $qb2 . ' ) = :cantidad1 OR (' . $qb3 . ') = :cantidad1')
		   ->andWhere('(' . $qb4 . ') = :cantidad2')
		   ->orderBy('c.cctrjerarquia')
		   ->setParameter('nctrestado', 1)
		   ->setParameter('cantidad1', 1)
		   ->setParameter('cantidad2', 0)
		   ->setParameter('nperusuaccestado2', 1)
		   ->setParameter('nrolctrestado3', 1)
		   ->setParameter('nperusuaccestado4', 0)
		   ->setParameter('nperusucodigo', $nperusucodigo);

		$query = $qb->getQuery();
		return $query->getResult();
	}

	public function buscarHijosPorUsuario($nperusucodigo, $nctrcodigopadre, $nctrtipo) {
		$qb = $this->_em->createQueryBuilder();
		$qb2 = $this->_em->createQueryBuilder();
		$qb3 = $this->_em->createQueryBuilder();
		$qb4 = $this->_em->createQueryBuilder();

		$dql2 = $qb2->select('COUNT(pu2)')
		            ->from('Sistema\Entity\Perusuario', 'pu2')
		            ->innerJoin('pu2.perusuaccesos', 'pua2')
		            ->innerJoin('pua2.control', 'c2')
		            ->where('pu2.nperusucodigo = :nperusucodigo')
		            ->andWhere('pua2.nperusuaccestado = :nperusuaccestado2')
		            ->andWhere('c2.nctrcodigo = c.nctrcodigo')
		            ->getDQL();

		$dql3 = $qb3->select('COUNT(pu3)')
		            ->from('Sistema\Entity\Perusuario', 'pu3')
		            ->innerJoin('pu3.rol', 'r3')
		            ->innerJoin('r3.rolcontrols', 'rc3')
		            ->innerJoin('rc3.control', 'c3')
		            ->where('pu3.nperusucodigo = :nperusucodigo')
		            ->andWhere('rc3.nrolctrestado = :nrolctrestado3')
		            ->andWhere('c3.nctrcodigo = c.nctrcodigo')
		            ->getDQL();

		$dql4 = $qb4->select('COUNT(pu4)')
		            ->from('Sistema\Entity\Perusuario', 'pu4')
		            ->innerJoin('pu4.perusuaccesos', 'pua4')
		            ->innerJoin('pua4.control', 'c4')
		            ->where('pu4.nperusucodigo = :nperusucodigo')
		            ->andWhere('pua4.nperusuaccestado = :nperusuaccestado4')
		            ->andWhere('c4.nctrcodigo = c.nctrcodigo')
		            ->getDQL();

		$qb->select('c')
		   ->from('Sistema\Entity\Control', 'c')
		   ->innerJoin('c.padre', 'p')
		   ->where('c.nctrestado = :nctrestado')
		   ->andWhere('p.nctrcodigo = :nctrcodigopadre')
		   ->andWhere('c.nctrtipo = :nctrtipo')
		   ->andWhere('(' . $qb2 . ' ) = :cantidad1 OR (' . $qb3 . ') = :cantidad1')
		   ->andWhere('(' . $qb4 . ') = :cantidad2')
		   ->orderBy('c.cctrjerarquia')
		   ->setParameter('nctrcodigopadre', $nctrcodigopadre)
		   ->setParameter('nctrestado', 1)
		   ->setParameter('nctrtipo', $nctrtipo)
		   ->setParameter('cantidad1', 1)
		   ->setParameter('cantidad2', 0)
		   ->setParameter('nperusuaccestado2', 1)
		   ->setParameter('nrolctrestado3', 1)
		   ->setParameter('nperusuaccestado4', 0)
		   ->setParameter('nperusucodigo', $nperusucodigo);

		$query = $qb->getQuery();
		return $query->getResult();
	}

	public function enviarTodos() {
		$qb = $this->_em->createQueryBuilder();

		$qb->select('c')
		   ->from('Sistema\Entity\Control', 'c')
		   ->where('c.padre IS NOT NULL')
		   ->andWhere('c.nctrestado = :nctrestado')
		   ->orderBy('c.cctrjerarquia')
		   ->setParameter('nctrestado', 1);

		$query = $qb->getQuery();
		return $query->getResult();
	}

	public function enviarPadres() {
		$qb = $this->_em->createQueryBuilder();

		$qb->select('c')
		   ->from('Sistema\Entity\Control', 'c')
		   ->where('c.padre IS NOT NULL')
		   ->andWhere('c.nctrtipo = :nctrtipo')
		   ->andWhere('c.nctrestado = :nctrestado')
		   ->orderBy('c.cctrjerarquia')
		   ->setParameter('nctrtipo', 5000)
		   ->setParameter('nctrestado', 1);

		$query = $qb->getQuery();
		return $query->getResult();
	}

	public function enviarHijos($nctrcodigo) {
		$qb = $this->_em->createQueryBuilder();

		$qb->select('c')
		   ->from('Sistema\Entity\Control', 'c')
		   ->where('c.padre = :nctrcodigo')
		   ->andWhere('c.nctrestado = :nctrestado')
		   ->orderBy('c.cctrjerarquia')
		   ->setParameter('nctrcodigo', $nctrcodigo)
		   ->setParameter('nctrestado', 1);

		$query = $qb->getQuery();
		return $query->getResult();
	}
}
