<?php

namespace Sistema\Repository;

use DoctrineORMModule\Paginator\Adapter\DoctrinePaginator as DoctrineAdapter;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator as ORMPaginator;
use Zend\Paginator\Paginator;

/**
 * DatosespacialesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosespacialesRepository extends EntityRepository {
	public function addFiltro($qb, $campos, $paginacion) {
		$expr = $qb->expr();
		$andX = $expr->andX();

		foreach ($campos as $columna => $valor) {
			if (strpos($columna, '-') !== false) {
				$colSeparadas = explode('-', $columna);

				$orX = $qb->expr()->orX();
				for ($i = 0; $i < count($colSeparadas); $i++) {
					$parametro = substr($colSeparadas[$i], strpos($colSeparadas[$i], '.') + 1);
					$orX->add($expr->like($colSeparadas[$i], ':' . $parametro));
					$qb->setParameter($parametro, '%' . $valor . '%');

					switch (true) {
						case ($i === 0):
							$concat = $qb->expr()->concat($colSeparadas[$i], $qb->expr()->literal(' '));
							break;
						case ($i < count($colSeparadas) - 1):
							$concat = $qb->expr()->concat($concat, $qb->expr()->concat($colSeparadas[$i], $qb->expr()->literal(' ')));
							break;
						case ($i === count($colSeparadas) - 1):
							$concat = $qb->expr()->concat($concat, $colSeparadas[$i]);
							break;
					}
				}

				$orX->add($expr->like($concat, ':concat'));
				$qb->setParameter('concat', '%' . $valor . '%');
				$andX->add($orX);
			} else {
				$parametro = substr($columna, strpos($columna, '.') + 1);
				$andX->add($expr->like($columna, ':' . $parametro));
				$qb->setParameter($parametro, '%' . $valor . '%');
			}

		}
		$qb->andWhere($andX);

		if ($paginacion) {
			$qb->setFirstResult($paginacion['inicio']);
			$qb->setMaxResults($paginacion['items']);
		}

		$query = $qb->getQuery();
		return $query;
	}

	public function buscar($campos, $paginacion) {
		$qb = $this->_em->createQueryBuilder();
		$qb->select('de')
		   ->from('Sistema\Entity\Datosespaciales', 'de')
		   ->where('de.ndatespestado != :ndatespestado')
		   ->orderBy('de.ndatespjerarquia', 'ASC')
		   ->setParameter('ndatespestado', 0);

		return $this->addFiltro($qb, $campos, $paginacion)->getResult();
	}

	public function getPaginador($campos, $paginacion) {
		$qb = $this->_em->createQueryBuilder();
		$qb->select('de')
		   ->from('Sistema\Entity\Datosespaciales', 'de')
		   ->where('de.ndatespestado != :ndatespestado')
		   ->orderBy('de.ndatespjerarquia', 'ASC')
		   ->setParameter('ndatespestado', 0);

		$query = $this->addFiltro($qb, $campos, $paginacion);

		$adapter = new DoctrineAdapter(new ORMPaginator($query));
		$paginator = new Paginator($adapter);
		$paginator->setDefaultItemCountPerPage($paginacion['items']);
		$paginator->setCurrentPageNumber($paginacion['pagina']);

		return $paginator;
	}

	public function buscarUltimoOrden() {
		$qb = $this->_em->createQueryBuilder();
		$qb->select('de.ndatespjerarquia')
		   ->from('Sistema\Entity\Datosespaciales', 'de')
		   ->orderBy('de.ndatespjerarquia', 'DESC')
		   ->setFirstResult(0)
		   ->setMaxResults(1);

		$query = $qb->getQuery();
		$tempResult = $query->getResult();
		if (!empty($tempResult)) {
			$result = $query->getSingleScalarResult();
		} else {
			$result = 0;
		}

		return $result;
	}

	public function buscarMenoresParaOrdenar($ndatespjerarquiaMay, $ndatespjerarquiaMin) {
		$qb = $this->_em->createQueryBuilder();
		$qb->select('de')
		   ->from('Sistema\Entity\Datosespaciales', 'de')
		   ->where('de.ndatespjerarquia > :ndatespjerarquiaMin')
		   ->andWhere('de.ndatespjerarquia <= :ndatespjerarquiaMay')
		   ->setParameter('ndatespjerarquiaMay', $ndatespjerarquiaMay)
		   ->setParameter('ndatespjerarquiaMin', $ndatespjerarquiaMin);

		$query = $qb->getQuery();
		return $query->getResult();
	}

	public function buscarMayoresParaOrdenar($ndatespjerarquiaMin, $ndatespjerarquiaMay) {
		$qb = $this->_em->createQueryBuilder();
		$qb->select('de')
		   ->from('Sistema\Entity\Datosespaciales', 'de')
		   ->where('de.ndatespjerarquia >= :ndatespjerarquiaMin')
		   ->andWhere('de.ndatespjerarquia < :ndatespjerarquiaMay')
		   ->setParameter('ndatespjerarquiaMin', $ndatespjerarquiaMin)
		   ->setParameter('ndatespjerarquiaMay', $ndatespjerarquiaMay);

		$query = $qb->getQuery();
		return $query->getResult();
	}
}
