<?php

namespace Sistema\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PdfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PdfRepository extends EntityRepository {
	public function buscarActivo($nmencodigo) {
		$qb = $this->_em->createQueryBuilder();
		$qb->select('p')
		   ->from('Sistema\Entity\Pdf', 'p')
		   ->where('p.menu = :nmencodigo')
		   ->andWhere('p.npdfestado != :npdfestado')
		   ->setParameter('nmencodigo', $nmencodigo)
		   ->setParameter('npdfestado', 0);

		$query = $qb->getQuery();
		return $query->getOneOrNullResult();
	}

	public function buscarPublicado($nmencodigo) {
		$qb = $this->_em->createQueryBuilder();
		$qb->select('p')
		   ->from('Sistema\Entity\Pdf', 'p')
		   ->where('p.menu = :nmencodigo')
		   ->andWhere('p.npdfestado = :npdfestado')
		   ->setParameter('nmencodigo', $nmencodigo)
		   ->setParameter('npdfestado', 2);

		$query = $qb->getQuery();
		return $query->getOneOrNullResult();
	}
}
