<?php

namespace Sistema\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HtmlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HtmlRepository extends EntityRepository {
	public function buscarActivo($nmencodigo) {
		$qb = $this->_em->createQueryBuilder();
		$qb->select('h')
		   ->from('Sistema\Entity\Html', 'h')
		   ->where('h.menu = :nmencodigo')
		   ->andWhere('h.nhtmlestado != :nhtmlestado')
		   ->setParameter('nmencodigo', $nmencodigo)
		   ->setParameter('nhtmlestado', 0);

		$query = $qb->getQuery();
		return $query->getOneOrNullResult();
	}

	public function buscarPublicado($nmencodigo) {
		$qb = $this->_em->createQueryBuilder();
		$qb->select('h')
		   ->from('Sistema\Entity\Html', 'h')
		   ->where('h.menu = :nmencodigo')
		   ->andWhere('h.nhtmlestado = :nhtmlestado')
		   ->setParameter('nmencodigo', $nmencodigo)
		   ->setParameter('nhtmlestado', 2);

		$query = $qb->getQuery();
		return $query->getOneOrNullResult();
	}
}
