<?php

namespace Sistema\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PerusuaccesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerusuaccesoRepository extends EntityRepository {

	public function buscarPorPk($nperusucodigo, $nctrcodigo) {
		$qb = $this->_em->createQueryBuilder();

		$qb->select('pua')
		   ->from('Sistema\Entity\Perusuacceso', 'pua')
		   ->innerJoin('pua.perusuario', 'pu')
		   ->innerJoin('pua.control', 'c')
		   ->where('pu.nperusucodigo = :nperusucodigo')
		   ->andWhere('c.nctrcodigo = :nctrcodigo')
		   ->setParameter('nperusucodigo', $nperusucodigo)
		   ->setParameter('nctrcodigo', $nctrcodigo);

		$query = $qb->getQuery();
		return $query->getOneOrNullResult();
	}

	public function buscarPorUsuario($nperusucodigo) {
		$qb = $this->_em->createQueryBuilder();

		$qb->select('pua')
		   ->from('Sistema\Entity\Perusuacceso', 'pua')
		   ->where('pua.perusuario = :nperusucodigo')
		   ->setParameter('nperusucodigo', $nperusucodigo);

		$query = $qb->getQuery();
		return $query->getResult();
	}
}
