<?php

namespace Sistema\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlRepository extends EntityRepository {
	public function buscarActivo($nmencodigo) {
		$qb = $this->_em->createQueryBuilder();
		$qb->select('u')
		   ->from('Sistema\Entity\Url', 'u')
		   ->where('u.menu = :nmencodigo')
		   ->andWhere('u.nurlestado != :nurlestado')
		   ->setParameter('nmencodigo', $nmencodigo)
		   ->setParameter('nurlestado', 0);

		$query = $qb->getQuery();
		return $query->getOneOrNullResult();
	}

	public function buscarPublicado($nmencodigo) {
		$qb = $this->_em->createQueryBuilder();
		$qb->select('u')
		   ->from('Sistema\Entity\Url', 'u')
		   ->where('u.menu = :nmencodigo')
		   ->andWhere('u.nurlestado = :nurlestado')
		   ->setParameter('nmencodigo', $nmencodigo)
		   ->setParameter('nurlestado', 2);

		$query = $qb->getQuery();
		return $query->getOneOrNullResult();
	}
}
